version: 2

jobs:
  build:
    docker:
      - image: cimg/node:12.20 
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "yarn.lock" }}
      #       - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn build

  publish:
    docker:
      - image: cimg/node:12.20 
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "yarn.lock" }}
      #       - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command: ./.circleci/publish-landkid-docker.sh
          name: Deploy to Docker

  unit_test:
    docker:
      - image: cimg/node:12.20 
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "yarn.lock" }}
      #       - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test:unit

  integration_test:
    docker:
      - image: cypress/base:12
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "yarn.lock" }}
      #       - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - .cache
          key: v1-dependencies-{{ checksum "yarn.lock" }}`
      - run:
          name: Cypress tests
          command: |
            node ./.circleci/create-cypress-env.js
            yarn test:integration:staging
          no_output_timeout: 30m
      - store_test_results:
          path: ./tests/integration/junit-reports
      - store_artifacts:
          path: ./tests/integration/screenshots

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: /^(?!pull\/).*$/
  unit_test:
    jobs:
      - unit_test
  integration_test:
    jobs:
      - hold:
          type: approval
      - integration_test:
          requires:
            - hold
